### ISSUE TITLE
Suggestions to make this more useful

### ISSUE THREAD

**Issue by Giwayume** [merovi-labs/svgtexture2d#1]
## Allow SVG "scale" to be independent of the output image width/height.

Whatever size the SVG imports as at a scale of 1 should always be the target display width/height. Adjusting the scale of the SVG would then inversely scale the actual sprite dimensions down to match the original image width/height. This makes it so the SVG scale is a "how far can I zoom in before I see pixels" setting, instead of another setting that makes your image bigger but still looks blurry the second you zoom in.

## Add a setting to automatically adjust scale based on the game's resolution.

Most people want to use vector graphics so their assets look good no matter the resolution the end user runs the game at. It would be good to automate this so it's not up to the game creator to have to figure it out. It could be a setting to set the scale as a percentage of the game window's width / height or a combination of the two such as max(width, height).

**Comment by ky000** [comment]
> ## Allow SVG "scale" to be independent of the output image width/height.
> Whatever size the SVG imports as at a scale of 1 should always be the target display width/height. Adjusting the scale of the SVG would then inversely scale the actual sprite dimensions down to match the original image width/height. This makes it so the SVG scale is a "how far can I zoom in before I see pixels" setting, instead of another setting that makes your image bigger but still looks blurry the second you zoom in.
> 
> ## Add a setting to automatically adjust scale based on the game's resolution.
> Most people want to use vector graphics so their assets look good no matter the resolution the end user runs the game at. It would be good to automate this so it's not up to the game creator to have to figure it out. It could be a setting to set the scale as a percentage of the game window's width / height or a combination of the two such as max(width, height).

That would be very interesting.. and would solve a lot of my current problems with svg

**Comment by raygoe** [comment]
Excellent point. I'll also see about attaching a signal to the resize of the framebuffer and reset the 1.0 to that in case the window scales.

**Comment by ky000** [comment]
> Excellent point. I'll also see about attaching a signal to the resize of the framebuffer and reset the 1.0 to that in case the window scales.

If this is possible I will redo my entire project using your addon. I hate how on different screens the quality of the game is so low.. and using mips makes everything a blur.

**Comment by PluckyDuck99** [comment]
> Excellent point. I'll also see about attaching a signal to the resize of the framebuffer and reset the 1.0 to that in case the window scales.

That seems interesting. Your plugin looks great. This would be quite an upgrade. I'll keep an eye on it! 🙂

**Comment by PluckyDuck99** [comment]
> Excellent point. I'll also see about attaching a signal to the resize of the framebuffer and reset the 1.0 to that in case the window scales.

Would this affect how the plugin works now? It's very useful for me. I can have the same .SVG file in different sizes on the screen. But of course, if it were possible to achieve the result described above, it would be nice

**Comment by ky000** [comment]
> Excellent point. I'll also see about attaching a signal to the resize of the framebuffer and reset the 1.0 to that in case the window scales.

Has this proposal had any updates? If there is any way to collaborate, please let me know

**Comment by raygoe** [comment]
With 1.1 you can now set a resolution along side sprite sizes:

![image](https://github.com/merovi-labs/svgtexture2d/assets/6090173/24781e89-b268-4cde-a892-0e1b214edd42)

The one on the left is 1.0 and the one on the right is 2.0 (based on the SVG dimensions when imported).

You can also set resolution. For instance, if you zoom in 400%, you can see they get pixelated:

![image](https://github.com/merovi-labs/svgtexture2d/assets/6090173/2d22d595-81a2-4688-bd15-410497cfca65)

However, if you set the resolution to 4.0, they're back to pixel-perfect:

![image](https://github.com/merovi-labs/svgtexture2d/assets/6090173/8a80d311-11be-46de-a63d-50f2bf7a70d7)

**Comment by raygoe** [comment]
As for the second part, I am trying to find a good way of doing that at the moment. I implemented it where it uses the viewport dimensions, but then I'd have to move the sprites as their offsets in the root node are absolute pixels instead of percentage of viewport, they crowd each other when you scale up.

I know on my game I'll be making use of a Camera and scaling the camera zoom as the viewport changes, so perhaps I'll add something like that for the second part.

**Comment by raygoe** [comment]
Okay I've got the second part of this done in v1.2. It contains a new node named `SVGCamera2D` that automatically handles zooming in when your project's stretch mode is set to disabled. It makes sure that your assets take up the same % of the viewport as they did in the original canvas.


https://github.com/merovi-labs/svgtexture2d/assets/6090173/59021332-20f8-4b5c-9e9d-85064cec3f30

The `SVGCamera2D` has a `zoom_changed` signal that the SVG Textures connect to and automatically regenerate when it changes.
