### ISSUE TITLE
Support for Control TextureRect equivalent

### ISSUE THREAD

**Issue by ilexl** [merovi-labs/svgtexture2d#10]
This plugin works amazing for Node2D textures but is there any chance of supporting Control based nodes like TextureRect TextureButton etc?

**Comment by raygoe** [comment]
The plugin already supports StyleBoxTextures using the SVGStyleBoxTexture class. I think you should be able to use that for buttons, etc.

**Comment by ilexl** [comment]
![image](https://github.com/user-attachments/assets/d4f7a96c-9b13-475d-b07d-8bc49b9990a3)
I had a look but couldn't get it to work with a texturebutton. I also cant use a Node2D for controls because the Node2D would ignore the rest of the UI scaling

**Comment by ilexl** [comment]
I have found a way to make the SVGTexture work with UI. It uses a custom script which takes Sprite2D Base and use that to control visuals. I wont add this here as we are using C# and this library is intended for gdscript
