### ISSUE TITLE
Fix Alpa Border on import settings

### ISSUE THREAD

**Issue by ky000** [merovi-labs/svgtexture2d#2]
Suggestion for addition: Fix alpha border option during texture import, my SVGs end up with slightly grayed corners, and enabling "fix alpha border" corrects the issue. It would be beneficial to have this option during the import process or adjust it during rastering/load in SvgSprite2d? I tried looking for something in the documentation but couldn't find anything.😅

![image](https://github.com/merovi-labs/svgtexture2d/assets/81387545/eaf68aa3-e41a-4265-8ba0-b252451bd31f)

**Comment by raygoe** [comment]
This is a good point. I'll fix this for 1.3

**Comment by raygoe** [comment]
This is fixed now. The plugin automatically fixes alpha borders when it generates the rasterized images.
