### ISSUE TITLE
Viewport Size / Scaling is not handled properly.

### ISSUE THREAD

**Issue by furrz** [merovi-labs/svgtexture2d#3]
SVGSprite2D doesn't account for viewport scaling. In a project where, for example, the stretch mode is set to canvas_items and aspect is set to expand, SVGs will be blurry when drawn in a window larger than the base canvas size.

A hackish (errs on the side of rendering at an unnecessarily high resolution) solution in SVGSprite2D.gd is pretty quick:

```gdscript
# ...

var viewport_scaling : float = 1.0

func _ready():
	var camera = get_viewport().get_camera_2d()

	if camera and camera is SVGCamera2D:
		(camera as SVGCamera2D).zoom_changed.connect(_on_zoom_change)

	get_viewport().size_changed.connect(_on_viewport_size_changed)
	_on_viewport_size_changed()

func _on_viewport_size_changed():
	var v = Vector2(get_viewport().size) / Vector2(get_tree().root.content_scale_size)
	viewport_scaling = max(v.x, v.y)
	_update_texture()

# ...
```

**Comment by raygoe** [comment]
On my project, I'm using the SVGCamera2D's zoom instead of the stretch mode which I found was a little unreliable. On the SVGCamera2D, I set the camera zoom to do roughly what stretch mode does but I can set the origin point of the canvas at the same time so I have better control. (Plus, my game has a Camera2D so it was a better fit.)

**Comment by PluckyDuck99** [comment]
> On my project, I'm using the SVGCamera2D's zoom instead of the stretch mode which I found was a little unreliable. On the SVGCamera2D, I set the camera zoom to do roughly what stretch mode does but I can set the origin point of the canvas at the same time so I have better control. (Plus, my game has a Camera2D so it was a better fit.)

How can I use SVGCamera2D with TileMap? I'm having trouble; unfortunately, the sprite's position relative to the TileMap ends up being different. I've tried several configurations.
