### ISSUE TITLE
Cannot get class 'SVGTexture2D'. Godot 4.2.1

### ISSUE THREAD

**Issue by kirkwoodwest** [merovi-labs/svgtexture2d#4]
Somehow I'm getting an error where it can't find this class... 

**  Cannot get class 'SVGTexture2D'.**

Been looking around for anything related to tools and resources but I'm just coming up milhouse. :(

Whats interesting is the tool seems to work "fine"... Somehow GODOT keeps throwing these errors for every SVG Imported using SVGTexture2D.

**Comment by PluckyDuck99** [comment]
> De alguma forma, estou recebendo um erro onde não é possível encontrar esta classe...
> 
> ** Não é possível obter a classe 'SVGTexture2D'.**
> 
> Tenho procurado por qualquer coisa relacionada a ferramentas e recursos, mas só agora estou encontrando Milhouse. :(
> 
> O interessante é que a ferramenta parece funcionar "bem"... De alguma forma, o GODOT continua gerando esses erros para cada SVG importado usando SVGTexture2D.

I’m encountering the same alerts. I’m looking into the source, but nothing seems to fix it. The functionality seems to be normal.

**Comment by PluckyDuck99** [comment]
> Somehow I'm getting an error where it can't find this class...
> 
> ** Cannot get class 'SVGTexture2D'.**
> 
> Been looking around for anything related to tools and resources but I'm just coming up milhouse. :(
> 
> Whats interesting is the tool seems to work "fine"... Somehow GODOT keeps throwing these errors for every SVG Imported using SVGTexture2D.

I’m encountering the same alerts. I’m looking into the source, but nothing seems to fix it. The functionality seems to be normal.

**Comment by raygoe** [comment]
This should get fixed in v4.3.

https://github.com/godotengine/godot/pull/92667

In the meantime I've included a couple workarounds, but it'll still require you to load the project twice.
